### ISSUE TITLE
Heroku: vos conseils pour le build ?

### ISSUE THREAD

**Issue by bfamchon** [miage-lille/api-design#1]
Hello !

J'en suis arrivé au Graal, le push sur Heroku ! Mon application est bien dans le nuage, les dynos & add-ons sont bien présents, mais l'application ne se build pas ( selon les logs )... Normal ! Babel se trouvant dans les "devDependencies", celles-ci ne sont pas installées par Heroku.
Je cherchais donc à savoir si il y avait des bonnes pratiques particulières pour le build & ce que vous conseillez de faire pour le tp !

**Comment by bfamchon** [comment]
J'ai réussi à build & start l'application sur heroku en intégrant les dépendances Babel dans "dependencies", il y a peut-être plus intéréssant comme manière de faire ! Voilà les accès:
https://qsi-tp2-bfamchon.herokuapp.com/
https://github.com/miage-lille/qsi-2-unip62/tree/master/postman

**Comment by oteku** [comment]
Pour le moment, vous pouvez ajouter cette variable d'environnement : `NPM_CONFIG_PRODUCTION=false`, soit avec heroku-cli `heroku config:set NPM_CONFIG_PRODUCTION=false` soit via le dashboard.
Ainsi heroku install les dépendences de developpement.

Dans un environnement de production, vous feriez le npm run build au sein de votre outil de CI (travis-ci par exemple), pour ne poussez sur Heroku que le build babel
